name: email_auth
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.0
  firebase_core: 2.20.0
  flutter: 
    sdk: flutter
  google_fonts: ^2.0.0
  get: ^4.6.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

fonts:
  -family: poppins
  fonts:
  -asset: assets/fonts/Poppins-Regular.ttf

